import { jsPDF } from "jspdf";

export type PdfMeta = {
  title: string;
  subtitle?: string;
  module?: string; // e.g. "Research Assistant"
  filename?: string;
};

// ResearchFlow brand colors (match src/styles.css)
const BRAND = { r: 37, g: 99, b: 235 }; // #2563EB
const INK = { r: 17, g: 24, b: 39 };
const MUTED = { r: 107, g: 114, b: 128 };

type Block =
  | { type: "h1" | "h2" | "h3" | "p"; text: string }
  | { type: "li"; text: string; indent: number }
  | { type: "hr" }
  | { type: "blank" };

function stripInline(s: string): string {
  return s
    .replace(/\*\*(.+?)\*\*/g, "$1")
    .replace(/\*(.+?)\*/g, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, "$1 ($2)");
}

function parseMarkdown(md: string): Block[] {
  const blocks: Block[] = [];
  const lines = md.replace(/\r\n/g, "\n").split("\n");
  for (const raw of lines) {
    const line = raw.trimEnd();
    if (!line.trim()) { blocks.push({ type: "blank" }); continue; }
    if (/^---+$/.test(line)) { blocks.push({ type: "hr" }); continue; }
    let m;
    if ((m = line.match(/^###\s+(.*)/))) { blocks.push({ type: "h3", text: stripInline(m[1]) }); continue; }
    if ((m = line.match(/^##\s+(.*)/))) { blocks.push({ type: "h2", text: stripInline(m[1]) }); continue; }
    if ((m = line.match(/^#\s+(.*)/))) { blocks.push({ type: "h1", text: stripInline(m[1]) }); continue; }
    if ((m = line.match(/^(\s*)[-*+]\s+(.*)/))) {
      const indent = Math.min(2, Math.floor(m[1].length / 2));
      blocks.push({ type: "li", text: stripInline(m[2]), indent });
      continue;
    }
    if ((m = line.match(/^(\s*)\d+\.\s+(.*)/))) {
      const indent = Math.min(2, Math.floor(m[1].length / 2));
      blocks.push({ type: "li", text: stripInline(m[2]), indent });
      continue;
    }
    blocks.push({ type: "p", text: stripInline(line) });
  }
  return blocks;
}

export function exportMarkdownToPDF(markdown: string, meta: PdfMeta) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const marginX = 56;
  const contentW = pageW - marginX * 2;
  let y = 0;

  const drawHeader = () => {
    doc.setFillColor(BRAND.r, BRAND.g, BRAND.b);
    doc.rect(0, 0, pageW, 64, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("ResearchFlow AI", marginX, 30);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(meta.module ?? "Report", marginX, 48);
    doc.text(new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" }),
      pageW - marginX, 48, { align: "right" });
    y = 96;
  };

  const drawFooter = (pageNum: number, totalPages: number) => {
    doc.setDrawColor(229, 231, 235);
    doc.setLineWidth(0.5);
    doc.line(marginX, pageH - 40, pageW - marginX, pageH - 40);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED.r, MUTED.g, MUTED.b);
    doc.text("Generated by ResearchFlow AI · researchflow.ai", marginX, pageH - 24);
    doc.text(`Page ${pageNum} / ${totalPages}`, pageW - marginX, pageH - 24, { align: "right" });
  };

  const ensureSpace = (h: number) => {
    if (y + h > pageH - 56) {
      doc.addPage();
      drawHeader();
    }
  };

  drawHeader();

  // Title
  doc.setTextColor(INK.r, INK.g, INK.b);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  const titleLines = doc.splitTextToSize(meta.title, contentW);
  ensureSpace(titleLines.length * 24);
  doc.text(titleLines, marginX, y);
  y += titleLines.length * 24;

  if (meta.subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(MUTED.r, MUTED.g, MUTED.b);
    const sl = doc.splitTextToSize(meta.subtitle, contentW);
    ensureSpace(sl.length * 14);
    doc.text(sl, marginX, y);
    y += sl.length * 14;
  }
  y += 8;

  // Accent rule
  doc.setDrawColor(BRAND.r, BRAND.g, BRAND.b);
  doc.setLineWidth(2);
  doc.line(marginX, y, marginX + 48, y);
  y += 20;

  doc.setTextColor(INK.r, INK.g, INK.b);
  const blocks = parseMarkdown(markdown);
  for (const b of blocks) {
    if (b.type === "blank") { y += 6; continue; }
    if (b.type === "hr") {
      ensureSpace(12);
      doc.setDrawColor(229, 231, 235);
      doc.setLineWidth(0.5);
      doc.line(marginX, y, pageW - marginX, y);
      y += 10;
      continue;
    }
    if (b.type === "h1") {
      doc.setFont("helvetica", "bold"); doc.setFontSize(16);
      doc.setTextColor(INK.r, INK.g, INK.b);
      const lines = doc.splitTextToSize(b.text, contentW);
      ensureSpace(lines.length * 20 + 8);
      doc.text(lines, marginX, y); y += lines.length * 20 + 4;
      continue;
    }
    if (b.type === "h2") {
      doc.setFont("helvetica", "bold"); doc.setFontSize(13);
      doc.setTextColor(BRAND.r, BRAND.g, BRAND.b);
      const lines = doc.splitTextToSize(b.text, contentW);
      ensureSpace(lines.length * 17 + 6);
      doc.text(lines, marginX, y); y += lines.length * 17 + 2;
      continue;
    }
    if (b.type === "h3") {
      doc.setFont("helvetica", "bold"); doc.setFontSize(11);
      doc.setTextColor(INK.r, INK.g, INK.b);
      const lines = doc.splitTextToSize(b.text, contentW);
      ensureSpace(lines.length * 15 + 4);
      doc.text(lines, marginX, y); y += lines.length * 15;
      continue;
    }
    if (b.type === "li") {
      doc.setFont("helvetica", "normal"); doc.setFontSize(10.5);
      doc.setTextColor(INK.r, INK.g, INK.b);
      const indent = b.indent * 14;
      const bulletX = marginX + indent;
      const textX = bulletX + 12;
      const lines = doc.splitTextToSize(b.text, contentW - indent - 12);
      ensureSpace(lines.length * 14);
      doc.setFillColor(BRAND.r, BRAND.g, BRAND.b);
      doc.circle(bulletX + 2, y - 3, 1.6, "F");
      doc.text(lines, textX, y);
      y += lines.length * 14;
      continue;
    }
    // paragraph
    doc.setFont("helvetica", "normal"); doc.setFontSize(10.5);
    doc.setTextColor(INK.r, INK.g, INK.b);
    const lines = doc.splitTextToSize(b.text, contentW);
    ensureSpace(lines.length * 14);
    doc.text(lines, marginX, y); y += lines.length * 14 + 4;
  }

  // Footers
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    drawFooter(i, total);
  }

  const fname = (meta.filename ?? meta.title).replace(/[^\w-]+/g, "_").slice(0, 80);
  doc.save(`${fname || "researchflow"}.pdf`);
}
